// Collision detail data — opens from KPI 3 ("Colisiones de lotes de material").
// Lots / cases where two surgeries needed the same kit on the same slot.

window.KPI_DATA.COLLISIONS = [
  {
    id: 'COL-2026-007',
    lot: 'Caja Laparoscopia Avanzada',
    lotRef: 'KIT-LAP-A2',
    surgeryA: { date: '2026-05-12', time: '08:30', spec: 'Cirugía General', proc: 'Colecistectomía laparoscópica', surgeon: 'Dr. Ramos',   or: 'Quirófano 2' },
    surgeryB: { date: '2026-05-12', time: '09:15', spec: 'Cirugía General', proc: 'Funduplicatura de Nissen',     surgeon: 'Dra. Marín',   or: 'Quirófano 4' },
    overlap: '45 min',
    resolution: 'Se usó lote alternativo KIT-LAP-A1 (disponible en almacén)',
    resolvedBy: 'M. García (Central)',
    resolvedAt: '2026-05-10 16:22',
    status: 'resolved',
  },
  {
    id: 'COL-2026-006',
    lot: 'Set Artroscopia Rodilla',
    lotRef: 'KIT-ART-R3',
    surgeryA: { date: '2026-05-09', time: '10:00', spec: 'Traumatología',   proc: 'Reconstrucción LCA',            surgeon: 'Dr. Soler',    or: 'Quirófano 1' },
    surgeryB: { date: '2026-05-09', time: '10:30', spec: 'Traumatología',   proc: 'Meniscectomía parcial',         surgeon: 'Dra. Puig',    or: 'Quirófano 3' },
    overlap: '1 h 20 min',
    resolution: 'Se desplazó cirugía B a las 13:30 tras esterilización del lote',
    resolvedBy: 'J. Vilar (Quirófano)',
    resolvedAt: '2026-05-07 11:05',
    status: 'resolved',
  },
  {
    id: 'COL-2026-005',
    lot: 'Caja Laparoscopia Básica',
    lotRef: 'KIT-LAP-B5',
    surgeryA: { date: '2026-05-05', time: '11:00', spec: 'Cirugía General', proc: 'Hernia inguinal laparoscópica', surgeon: 'Dr. Ramos',    or: 'Quirófano 2' },
    surgeryB: { date: '2026-05-05', time: '11:45', spec: 'Cirugía General', proc: 'Apendicectomía laparoscópica',  surgeon: 'Dra. Costa',   or: 'Quirófano 5' },
    overlap: '50 min',
    resolution: 'Se duplicó el lote (KIT-LAP-B6 prestado desde almacén general)',
    resolvedBy: 'M. García (Central)',
    resolvedAt: '2026-05-04 09:30',
    status: 'resolved',
  },
  {
    id: 'COL-2026-004',
    lot: 'Set Columna Posterior',
    lotRef: 'KIT-COL-P1',
    surgeryA: { date: '2026-05-03', time: '08:00', spec: 'Traumatología',   proc: 'Discectomía L4-L5',             surgeon: 'Dra. Bonet',   or: 'Quirófano 1' },
    surgeryB: { date: '2026-05-03', time: '12:30', spec: 'Traumatología',   proc: 'Artrodesis lumbar',             surgeon: 'Dr. Soler',    or: 'Quirófano 1' },
    overlap: '15 min · ciclo de esteril.',
    resolution: 'Se priorizó turno B; cirugía A se adelantó 30 min',
    resolvedBy: 'J. Vilar (Quirófano)',
    resolvedAt: '2026-05-02 17:15',
    status: 'resolved',
  },
  {
    id: 'COL-2026-003',
    lot: 'Caja Microcirugía ORL',
    lotRef: 'KIT-ORL-M2',
    surgeryA: { date: '2026-04-28', time: '09:30', spec: 'ORL',             proc: 'Septoplastia + turbinoplastia', surgeon: 'Dr. Tomás',    or: 'Quirófano 3' },
    surgeryB: { date: '2026-04-28', time: '10:00', spec: 'ORL',             proc: 'Polipectomía endoscópica',      surgeon: 'Dra. León',    or: 'Quirófano 3' },
    overlap: '35 min',
    resolution: 'Se reorganizó la programación: B pasó a las 12:30',
    resolvedBy: 'M. García (Central)',
    resolvedAt: '2026-04-27 14:48',
    status: 'resolved',
  },
  {
    id: 'COL-2026-002',
    lot: 'Set Cataratas Premium',
    lotRef: 'KIT-OFT-C4',
    surgeryA: { date: '2026-04-22', time: '08:00', spec: 'Oftalmología',    proc: 'Facoemulsificación + LIO',      surgeon: 'Dr. Albert',   or: 'Quirófano 6' },
    surgeryB: { date: '2026-04-22', time: '08:30', spec: 'Oftalmología',    proc: 'Facoemulsificación + LIO',      surgeon: 'Dra. Soto',    or: 'Quirófano 6' },
    overlap: 'Turno consecutivo · sin tiempo de esteril.',
    resolution: 'Se asignó KIT-OFT-C5 (segundo set disponible en oftalmología)',
    resolvedBy: 'Central (auto)',
    resolvedAt: '2026-04-20 08:15',
    status: 'resolved',
  },
  {
    id: 'COL-2026-001',
    lot: 'Caja Vascular Periférico',
    lotRef: 'KIT-VAS-P1',
    surgeryA: { date: '2026-04-15', time: '08:30', spec: 'Cirugía Vascular', proc: 'Bypass femoropoplíteo',         surgeon: 'Dr. Vidal',    or: 'Quirófano 4' },
    surgeryB: { date: '2026-04-15', time: '14:00', spec: 'Cirugía Vascular', proc: 'Fístula arteriovenosa',         surgeon: 'Dra. Esteve',  or: 'Quirófano 4' },
    overlap: '40 min · ciclo de esteril.',
    resolution: 'Se aceleró el ciclo en autoclave de emergencia (45 min)',
    resolvedBy: 'M. García (Central)',
    resolvedAt: '2026-04-14 19:30',
    status: 'resolved',
  },
];
