// 11 KPIs + 9 familias de normativa + 5 vistas de rol (incluye "Todos")
// Datos demo cargados con cifras plausibles.

window.KPI_DATA = (function () {
  // Familias de normativa (agrupadas para mantener el filtro usable).
  // El texto exacto del Excel se conserva en `detail`.
  const NORMS = {
    rd192: {
      id: 'rd192', short: 'RD 192/2023', full: 'RD 192/2023 — Productos sanitarios',
      family: 'Estatal', color: 'var(--brand-600)',
    },
    mdr: {
      id: 'mdr', short: 'MDR 2017/745', full: 'Reg. (UE) 2017/745 — MDR',
      family: 'Europea', color: 'var(--blue-700)',
    },
    ley41: {
      id: 'ley41', short: 'Ley 41/2002', full: 'Ley 41/2002 — Autonomía del paciente',
      family: 'Estatal', color: '#9333EA',
    },
    ley39: {
      id: 'ley39', short: 'Ley 39/2015', full: 'Ley 39/2015 — Administración electrónica',
      family: 'Estatal', color: '#7C3AED',
    },
    iso13485: {
      id: 'iso13485', short: 'ISO 13485', full: 'UNE-EN ISO 13485 — Gestión de calidad PS',
      family: 'Norma técnica', color: '#0E7490',
    },
    esterilTec: {
      id: 'esterilTec', short: 'Esteril. técnica', full: 'UNE-EN 285 · ISO 17665 · ISO 11138 · ISO 15883',
      family: 'Norma técnica', color: '#0F766E',
    },
    iso14001: {
      id: 'iso14001', short: 'ISO 14001 / EMAS', full: 'UNE-EN ISO 14001 · Reg. EMAS 761/2001',
      family: 'Medioambiente', color: '#15803D',
    },
    catsalut: {
      id: 'catsalut', short: 'CatSalut', full: 'Acreditación CatSalut 9c-02-E54',
      family: 'Autonómica', color: '#B45309',
    },
    guiasAuto: {
      id: 'guiasAuto', short: 'Guías autonómicas', full: 'C-La Mancha · SERGAS · País Vasco · SEDE',
      family: 'Autonómica', color: '#BE123C',
    },
  };

  const CATS = {
    central:   { id: 'central',  label: 'Eficiencia de la central',  short: 'Central',     color: 'var(--brand-600)' },
    quiro:     { id: 'quiro',    label: 'Eficiencia de quirófano',   short: 'Quirófano',   color: 'var(--blue-700)' },
    seguridad: { id: 'seguridad',label: 'Seguridad del paciente',    short: 'Seguridad',   color: '#BE123C' },
    registro:  { id: 'registro', label: 'Registro documental',       short: 'Registro',    color: '#0E7490' },
    sosten:    { id: 'sosten',   label: 'Sostenibilidad',            short: 'Sostenib.',   color: '#15803D' },
  };

  const KPIS = [
    { n: 1, cat: 'central', icon: 'lost', title: 'Instrumental perdido', sub: 'y coste asociado',
      value: '0,8%', extra: '12 400 €', target: 'Definir internamente', status: 'warn', trend: +0.1, trendUnit: 'pp',
      norms: ['rd192','mdr','guiasAuto'],
      whatMeasures: 'Piezas no localizadas / Inventario total × 100. Coste = Σ precio de compra de cada pieza perdida.',
      whyMatters: 'Detecta fugas de inventario y mide su impacto económico real. Cuantifica el coste evitable de reposición.',
      dataNeeded: 'Inventario en Armoni · Precio de compra por instrumento (lo aporta el hospital).',
      roles: ['central','calidad','gerencia'],
      detail: [
        'RD 192/2023 Art. 8.d — trazabilidad',
        'Reg. (UE) 2017/745 Art. 17 — mantenimiento',
        'Guía Castilla-La Mancha — reducción de pérdidas',
      ],
    },
    { n: 2, cat: 'central', icon: 'expire', title: 'Re-esterilización por caducidad', sub: '',
      value: '0,6%', target: '< 1%', status: 'ok', trend: -0.2, trendUnit: 'pp',
      norms: ['rd192','iso14001','guiasAuto'],
      whatMeasures: 'Productos re-esterilizados por caducidad / Total esterilizados × 100.',
      whyMatters: 'Mide la planificación del proceso. Cuanto más bajo, mejor uso del material y menos reprocesado innecesario.',
      dataNeeded: 'Nativo de Armoni.',
      roles: ['central','calidad'],
      detail: [
        'RD 192/2023 Art. 8.a — sistema de calidad',
        'Guías autonómicas — rotación por caducidad',
        'UNE-EN ISO 14001 — minimización de residuos',
      ],
    },
    { n: 3, cat: 'central', icon: 'collision', title: 'Colisiones de lotes de material', sub: 'y resolución a tiempo',
      value: '7', extra: '100% resueltas', target: '100% resueltas', status: 'ok', trend: -1, trendUnit: '',
      norms: ['rd192','ley41'],
      whatMeasures: 'Nº de alertas (dos cirugías necesitan el mismo lote de material) y ratio de colisiones resueltas a tiempo / total.',
      whyMatters: 'Mide la capacidad del módulo de planificación de detectar y resolver conflictos antes de impactar quirófano.',
      dataNeeded: 'Nativo de Armoni · módulo de planificación.',
      roles: ['central','quirofano'],
      detail: [
        'RD 192/2023 Art. 8.a — sistema de calidad',
        'Ley 41/2002 — seguridad del paciente (indirecta)',
      ],
    },
    { n: 4, cat: 'quiro', icon: 'usage', title: 'Utilización del instrumental enviado', sub: 'mide sobrepreparación',
      value: '62%', target: 'Definir internamente', status: 'warn', trend: +2, trendUnit: 'pp',
      norms: ['rd192','ley41','guiasAuto'],
      whatMeasures: 'Instrumentos utilizados / Instrumentos enviados × 100. Si es bajo, se envía material que no se necesita (sobrepreparación).',
      whyMatters: 'Optimiza el dimensionado de sets y reduce coste de reprocesado innecesario.',
      dataNeeded: 'Nativo de Armoni.',
      roles: ['quirofano','central','gerencia'],
      detail: [
        'Ley 41/2002 — seguridad del paciente (indirecta)',
        'RD 192/2023 Art. 8.a — sistema de calidad',
        'Guía Castilla-La Mancha — eficiencia',
      ],
    },
    { n: 5, cat: 'quiro', icon: 'request', title: 'Peticiones de material durante la intervención', sub: 'media por intervención',
      value: '1,3', extra: 'instr./interv.', target: 'Reducir progresivamente', status: 'warn', trend: -0.2, trendUnit: '',
      norms: ['rd192','ley41'],
      whatMeasures: 'Nº medio de instrumentos adicionales pedidos durante la cirugía por intervención.',
      whyMatters: 'Si la media es alta, los sets están infradimensionados o mal configurados — riesgo de demora quirúrgica.',
      dataNeeded: 'Nativo de Armoni · registro de peticiones en quirófano.',
      roles: ['quirofano','central'],
      detail: [
        'Ley 41/2002 — seguridad del paciente (indirecta)',
        'RD 192/2023 Art. 8.a — sistema de calidad',
      ],
    },
    { n: 6, cat: 'seguridad', icon: 'shield', title: 'No conformidades en material estéril', sub: '',
      value: '0,4%', extra: '7 incid.', target: 'Definir (exigido en auditoría)', status: 'alert', trend: +0.1, trendUnit: 'pp',
      norms: ['rd192','iso13485','catsalut','guiasAuto'],
      whatMeasures: 'Incidencias en material estéril entregado / Total entregas × 100. Estándar CatSalut 9c-02-E54.',
      whyMatters: 'Exigido en auditoría. Mide la calidad final del material que llega a paciente.',
      dataNeeded: 'Nativo de Armoni.',
      roles: ['calidad','central','gerencia'],
      detail: [
        'RD 192/2023 Art. 8.a — sistema de calidad',
        'UNE-EN ISO 13485 — gestión de no conformidades',
        'Guía SERGAS Anexo VII — indicadores de calidad',
        'Guía Castilla-La Mancha — registrar incidencias',
        'Acreditación CatSalut',
      ],
    },
    { n: 7, cat: 'seguridad', icon: 'trace', title: 'Trazabilidad completa', sub: 'intervención → esteril. → lavado',
      value: '99,2%', target: '100%', status: 'warn', trend: +0.4, trendUnit: 'pp',
      norms: ['rd192','mdr','ley41','ley39','iso13485','guiasAuto'],
      whatMeasures: 'Instrumentos con traza completa (intervención → esterilización → lavado) / Total usados × 100.',
      whyMatters: 'Obligatorio por MDR. El punto de rotura de traza indica pérdida de control del proceso.',
      dataNeeded: 'Nativo de Armoni.',
      roles: ['calidad','central','quirofano','gerencia'],
      detail: [
        'RD 192/2023 Art. 8.d — trazabilidad (10 años)',
        'Reg. (UE) 2017/745 Art. 18 — identificación',
        'Ley 41/2002 Art. 14.2, 17.1 — historia clínica',
        'Ley 39/2015 Art. 17 — archivo electrónico',
        'UNE-EN ISO 13485 — trazabilidad de producto sanitario',
        'Todas las guías autonómicas',
      ],
    },
    { n: 8, cat: 'registro', icon: 'checklist', title: 'Cumplimiento del protocolo de controles', sub: '¿Se ha hecho lo que toca?',
      value: '97%', target: '100%', status: 'warn', trend: -1, trendUnit: 'pp',
      norms: ['rd192','esterilTec','guiasAuto'],
      whatMeasures: 'Controles realizados / Controles que debían realizarse × 100. Incluye Bowie-Dick, indicador químico y biológico.',
      whyMatters: 'Mide disciplina de protocolo. CatSalut exige 100%. Si bajamos del 100% es indicador de problema operativo.',
      dataNeeded: 'Nativo de Armoni.',
      roles: ['central','calidad'],
      detail: [
        'RD 192/2023 Art. 8.a — controles procedentes',
        'UNE-EN 285 · UNE-EN ISO 17665',
        'UNE-EN ISO 11138 · UNE-EN ISO 15883',
        'Guía SERGAS Anexo VII — indicadores',
        'Todas las guías autonómicas — frecuencias',
      ],
    },
    { n: 9, cat: 'registro', icon: 'pass', title: 'Bowie-Dick conformes', sub: 'penetración de vapor',
      value: '99,4%', target: '≥ 99%', status: 'ok', trend: +0.1, trendUnit: 'pp',
      norms: ['rd192','esterilTec'],
      whatMeasures: 'Tests Bowie-Dick con resultado conforme / Total tests Bowie-Dick realizados × 100. Se realiza 1 test diario en cada autoclave de vacío previo, antes del primer ciclo.',
      whyMatters: 'Valida que el autoclave alcanza vacío completo y que el vapor penetra uniformemente. Un Bowie-Dick fallido bloquea el uso del autoclave hasta su revisión.',
      dataNeeded: 'Nativo de Armoni vía integración con autoclaves.',
      roles: ['central','calidad'],
      detail: [
        'UNE-EN 285 — esterilizadores de vapor grandes',
        'UNE-EN ISO 17665 — criterios de aceptación',
        'RD 192/2023 Art. 8.a — sistema de calidad',
        'Guía SERGAS Anexo VII — indicadores de resultado',
      ],
    },
    { n: 10, cat: 'registro', icon: 'pass', title: 'Control biológico conforme', sub: 'ausencia de crecimiento',
      value: '100%', target: '100%', status: 'ok', trend: 0, trendUnit: 'pp',
      norms: ['rd192','esterilTec','iso13485'],
      whatMeasures: 'Controles biológicos con resultado conforme (sin crecimiento) / Total controles biológicos realizados × 100. Se hace semanalmente en vapor, en cada carga con implantables y en cada carga de OE/plasma.',
      whyMatters: 'Es la validación definitiva de que el ciclo de esterilización ha sido efectivo. Un fallo obliga a retirar todo el material procesado en ese ciclo.',
      dataNeeded: 'Nativo de Armoni vía integración con incubadora biológica.',
      roles: ['central','calidad'],
      detail: [
        'UNE-EN ISO 11138 — indicadores biológicos',
        'UNE-EN ISO 17665 — criterios de aceptación',
        'UNE-EN ISO 13485 — gestión de calidad PS',
        'RD 192/2023 Art. 8.a — sistema de calidad',
      ],
    },
    { n: 11, cat: 'sosten', icon: 'paper', title: 'Ahorro de papel por digitalización', sub: 'acumulado anual',
      value: '4 820', extra: '1 156 €', target: '—', status: 'ok', trend: +320, trendUnit: '/mes',
      norms: ['ley39','iso14001','guiasAuto'],
      whatMeasures: 'Nº de registros digitales generados = documentos físicos evitados. Coste evitado = Nº docs × coste unitario de impresión.',
      whyMatters: 'Reporte ESG. Demuestra el ahorro tangible de digitalización al comité de dirección.',
      dataNeeded: 'Conteo nativo en Armoni. Coste de impresión (opcional, aporta el hospital).',
      roles: ['gerencia','calidad'],
      detail: [
        'Ley 39/2015 — administración electrónica',
        'UNE-EN ISO 14001 — gestión medioambiental',
        'Guía SEDE 2023 — sostenibilidad y embalaje',
      ],
    },
    { n: 12, cat: 'sosten', icon: 'resources', title: 'Consumo por reprocesado de material', sub: 'lavado · esterilización · envío',
      value: '88 L', extra: '6,4 kWh', target: 'Definir baseline', status: 'na', trend: 0, trendUnit: '',
      dualLayout: { left: { n: '6,4', u: 'kWh' }, right: { n: '88', u: 'L' } },
      norms: ['iso14001','guiasAuto'],
      whatMeasures: 'Consumo medio de agua (L) y energía (kWh) por cada ciclo completo de reprocesado del material: lavado, secado, esterilización, almacenaje, envío a quirófano y devolución.',
      whyMatters: 'Línea base de huella ambiental y coste energético de todo el flujo del instrumental. Permite identificar qué etapa del proceso consume más y dónde optimizar. Base para reporte EMAS.',
      dataNeeded: 'Contadores del hospital (agua y energía por equipo: lavadoras, autoclaves, almacén) + trazabilidad del ciclo de cada lote (nativo Armoni).',
      roles: ['gerencia','calidad'],
      detail: [
        'UNE-EN ISO 14001 — gestión medioambiental',
        'Reglamento EMAS 761/2001 — auditoría medioambiental',
        'Guía Castilla-La Mancha — control medioambiental',
        'Guía País Vasco — gestión de residuos',
      ],
    },
  ];

  // 5 vistas: incluye "Todos"
  const ROLES = {
    todos:      { id: 'todos',     label: 'Vista completa', short: 'Todos',     order: ['seguridad','registro','central','quiro','sosten'] },
    calidad:    { id: 'calidad',   label: 'Resp. Calidad',  short: 'Calidad',   order: ['seguridad','registro','central','quiro','sosten'] },
    central:    { id: 'central',   label: 'Resp. Central',  short: 'Central',   order: ['central','registro','seguridad','quiro','sosten'] },
    quirofano:  { id: 'quirofano', label: 'Resp. Quirófano', short: 'Quirófano',order: ['quiro','seguridad','central','registro','sosten'] },
    gerencia:   { id: 'gerencia',  label: 'Gerencia',       short: 'Gerencia',  order: ['sosten','seguridad','central','quiro','registro'] },
  };

  // Sparkline demo data por KPI (12 puntos)
  const SPARKS = {
    1: [0.6,0.7,0.65,0.7,0.75,0.7,0.7,0.75,0.7,0.7,0.75,0.8],
    2: [0.9,0.85,0.8,0.85,0.75,0.7,0.75,0.7,0.65,0.7,0.65,0.6],
    3: [12,10,11,9,10,8,9,8,9,7,8,7],
    4: [55,57,58,56,59,58,60,59,61,60,61,62],
    5: [1.7,1.6,1.6,1.5,1.5,1.5,1.4,1.4,1.4,1.3,1.3,1.3],
    6: [0.2,0.2,0.25,0.3,0.3,0.3,0.35,0.35,0.4,0.4,0.35,0.4],
    7: [98.4,98.6,98.5,98.7,98.7,98.8,98.9,99.0,99.0,98.9,99.1,99.2],
    8: [99,99,98,98,98,98,97,98,98,97,97,97],
    9: [99.5,99.6,99.4,99.6,99.3,99.5,99.4,99.6,99.4,99.5,99.3,99.4],
    10:[100,100,100,100,100,100,100,100,100,100,100,100],
    11:[280,300,310,330,340,360,380,390,410,430,450,490],
    12:[88,89,88,87,89,88,87,88,89,88,88,87],
  };

  // Weekly evolution data — 12 weeks (W14 → W25 of 2026, last 3 months)
  const WEEKLY = {
    1: [0.5,0.6,0.6,0.7,0.65,0.7,0.7,0.75,0.7,0.75,0.8,0.8],
    2: [0.95,0.9,0.85,0.85,0.8,0.75,0.75,0.7,0.65,0.65,0.6,0.6],
    3: [12,11,10,11,9,10,9,8,9,7,8,7],
    4: [55,56,57,58,58,59,60,60,61,61,62,62],
    5: [1.8,1.7,1.6,1.6,1.6,1.5,1.4,1.4,1.4,1.3,1.3,1.3],
    6: [0.20,0.22,0.25,0.28,0.30,0.30,0.32,0.35,0.38,0.40,0.40,0.42],
    7: [98.3,98.5,98.6,98.6,98.7,98.8,98.9,99.0,99.1,99.0,99.1,99.2],
    8: [99,99,99,98,98,98,98,97,97,97,97,97],
    9: [99.5,99.6,99.4,99.6,99.3,99.5,99.4,99.6,99.4,99.5,99.3,99.4],
    10:[100,100,100,100,100,100,100,100,100,100,100,100],
    11:[280,300,310,330,340,360,380,390,410,430,450,490],
    12:[88,89,88,87,89,88,87,88,89,88,88,87],
  };

  return { NORMS, CATS, KPIS, ROLES, SPARKS, WEEKLY };
})();

// Detail data for the inventory-cost modal (KPI 1)
window.KPI_DATA.LOST_INSTRUMENTS = [
  { ref:'INS-1042', name:'Pinza Kocher recta 16 cm',        cat:'Pinzas',         qty:5, unit:145,  lastSeen:'2026-04-22', or:'Quirófano 3'  },
  { ref:'INS-1058', name:'Tijera Mayo recta 14 cm',          cat:'Tijeras',        qty:3, unit:89,   lastSeen:'2026-05-02', or:'Quirófano 1'  },
  { ref:'INS-2031', name:'Disector Metzenbaum 18 cm',        cat:'Disectores',     qty:1, unit:122,  lastSeen:'2026-04-18', or:'Quirófano 2'  },
  { ref:'INS-2210', name:'Portaagujas Mayo-Hegar 16 cm',     cat:'Portaagujas',    qty:4, unit:178,  lastSeen:'2026-04-29', or:'Quirófano 4'  },
  { ref:'INS-3115', name:'Separador Farabeuf adulto',        cat:'Separadores',    qty:2, unit:64,   lastSeen:'2026-04-11', or:'Quirófano 3'  },
  { ref:'INS-3401', name:'Pinza Adson con dientes 12 cm',    cat:'Pinzas',         qty:5, unit:52,   lastSeen:'2026-05-06', or:'Quirófano 1'  },
  { ref:'INS-4022', name:'Cucharilla Volkmann nº 2',         cat:'Cucharillas',    qty:1, unit:41,   lastSeen:'2026-03-30', or:'Quirófano 2'  },
  { ref:'INS-4109', name:'Pinza mosquito Halsted 12 cm',     cat:'Hemostáticas',   qty:8, unit:38,   lastSeen:'2026-05-08', or:'Quirófano 1'  },
  { ref:'INS-5001', name:'Especulum Cusco mediano',          cat:'Especulares',    qty:2, unit:75,   lastSeen:'2026-04-15', or:'Quirófano 5'  },
  { ref:'INS-5320', name:'Bisturí mango nº 4',                cat:'Mangos bisturí', qty:6, unit:28,   lastSeen:'2026-05-10', or:'Quirófano 2'  },
  { ref:'INS-6080', name:'Pinza Allis 5×6 dientes 16 cm',    cat:'Pinzas',         qty:4, unit:95,   lastSeen:'2026-04-25', or:'Quirófano 4'  },
  { ref:'INS-6502', name:'Pinza intestinal Doyen recta',     cat:'Pinzas',         qty:3, unit:142,  lastSeen:'2026-04-02', or:'Quirófano 3'  },
  { ref:'INS-7012', name:'Disector Lahey 19 cm',             cat:'Disectores',     qty:2, unit:138,  lastSeen:'2026-04-17', or:'Quirófano 2'  },
  { ref:'INS-7244', name:'Set retracción St. Mark adulto',   cat:'Separadores',    qty:2, unit:1820, lastSeen:'2026-03-22', or:'Quirófano 4'  },
  { ref:'INS-7501', name:'Aguja Veress 12 cm',                cat:'Laparoscopia',   qty:5, unit:95,   lastSeen:'2026-05-04', or:'Quirófano 1'  },
  { ref:'INS-8120', name:'Pinza grasper laparoscópica 5 mm', cat:'Laparoscopia',   qty:3, unit:685,  lastSeen:'2026-04-30', or:'Quirófano 5'  },
  { ref:'INS-8204', name:'Trócar reutilizable 10 mm',         cat:'Laparoscopia',   qty:4, unit:410,  lastSeen:'2026-04-09', or:'Quirófano 5'  },
  { ref:'INS-9015', name:'Pinza biopsia rígida 5 mm',        cat:'Endoscopia',     qty:2, unit:320,  lastSeen:'2026-04-23', or:'Quirófano 2'  },
];
