// Paper-record types digitized across the full reprocessing cycle.
// Opens from KPI 11 ("Ahorro de papel por digitalización").

window.KPI_DATA.DIGITIZATION = [
  {
    id: 'REG-LAV-01',
    name: 'Hoja de recepción y descontaminación',
    stage: 'lavado',
    desc: 'Registro de cada lote sucio recibido en la zona de descontaminación: hora, procedencia, responsable.',
    monthlyDocs: 612,
    pagesPerDoc: 1,
    norm: 'RD 192/2023 Art. 8.a',
    required: true,
  },
  {
    id: 'REG-LAV-02',
    name: 'Hoja de carga de lavadora',
    stage: 'lavado',
    desc: 'Cada ciclo de lavado mecánico: programa, productos químicos, indicador de proceso (TOSI).',
    monthlyDocs: 384,
    pagesPerDoc: 1,
    norm: 'UNE-EN ISO 15883',
    required: true,
  },
  {
    id: 'REG-EMP-01',
    name: 'Hoja de empaquetado',
    stage: 'empaquetado',
    desc: 'Inventario de cada paquete/contenedor: instrumentos, integridad, indicador interno.',
    monthlyDocs: 1042,
    pagesPerDoc: 1,
    norm: 'UNE-EN ISO 11607',
    required: true,
  },
  {
    id: 'REG-EST-01',
    name: 'Hoja de carga de autoclave',
    stage: 'esterilización',
    desc: 'Composición de cada ciclo: paquetes incluidos, parámetros, registro gráfico del ciclo.',
    monthlyDocs: 318,
    pagesPerDoc: 2,
    norm: 'UNE-EN 285',
    required: true,
  },
  {
    id: 'REG-EST-02',
    name: 'Test Bowie-Dick diario',
    stage: 'esterilización',
    desc: 'Tira de control de penetración de vapor en autoclaves de prevacío. 1 por equipo/día.',
    monthlyDocs: 124,
    pagesPerDoc: 1,
    norm: 'UNE-EN 285',
    required: true,
  },
  {
    id: 'REG-EST-03',
    name: 'Indicador químico por paquete',
    stage: 'esterilización',
    desc: 'Etiqueta con viraje de color que valida que el paquete fue sometido al ciclo correcto.',
    monthlyDocs: 1042,
    pagesPerDoc: 1,
    norm: 'UNE-EN ISO 11140',
    required: true,
  },
  {
    id: 'REG-EST-04',
    name: 'Control biológico semanal',
    stage: 'esterilización',
    desc: 'Esporas Geobacillus en vapor (semanal) + cada carga con implantables + cada carga OE/plasma.',
    monthlyDocs: 56,
    pagesPerDoc: 2,
    norm: 'UNE-EN ISO 11138',
    required: true,
  },
  {
    id: 'REG-ALM-01',
    name: 'Registro de almacenaje y rotación',
    stage: 'almacenaje',
    desc: 'Entradas y salidas del almacén estéril, control de caducidades y rotación FEFO.',
    monthlyDocs: 472,
    pagesPerDoc: 1,
    norm: 'RD 192/2023 Art. 8.a',
    required: true,
  },
  {
    id: 'REG-QUI-01',
    name: 'Petición de material a quirófano',
    stage: 'envío',
    desc: 'Solicitud previa a cada cirugía: lotes y sets requeridos, hora prevista.',
    monthlyDocs: 286,
    pagesPerDoc: 1,
    norm: 'Guía SERGAS Anexo VII',
    required: false,
  },
  {
    id: 'REG-QUI-02',
    name: 'Albarán de entrega a quirófano',
    stage: 'envío',
    desc: 'Confirmación firmada por enfermería: material recibido, integridad de los envoltorios.',
    monthlyDocs: 286,
    pagesPerDoc: 1,
    norm: 'Ley 41/2002',
    required: true,
  },
  {
    id: 'REG-QUI-03',
    name: 'Trazabilidad intraquirúrgica',
    stage: 'envío',
    desc: 'Etiqueta del lote pegada en la historia clínica del paciente (trazabilidad MDR).',
    monthlyDocs: 286,
    pagesPerDoc: 1,
    norm: 'Reg. (UE) 2017/745 Art. 18',
    required: true,
  },
  {
    id: 'REG-DEV-01',
    name: 'Hoja de devolución a central',
    stage: 'devolución',
    desc: 'Material devuelto tras la cirugía: lote, hora, incidencias en el uso.',
    monthlyDocs: 286,
    pagesPerDoc: 1,
    norm: 'RD 192/2023 Art. 8.a',
    required: true,
  },
  {
    id: 'REG-NC-01',
    name: 'Parte de no conformidad',
    stage: 'incidencias',
    desc: 'Registro de incidencias detectadas en material estéril: rotura, contaminación, faltantes.',
    monthlyDocs: 24,
    pagesPerDoc: 2,
    norm: 'UNE-EN ISO 13485',
    required: true,
  },
  {
    id: 'REG-MAN-01',
    name: 'Registro de mantenimientos preventivos',
    stage: 'mantenimiento',
    desc: 'Mantenimientos programados de autoclaves, lavadoras y selladoras (interno + SAT).',
    monthlyDocs: 18,
    pagesPerDoc: 3,
    norm: 'Reg. (UE) 2017/745 Art. 17',
    required: true,
  },
];

window.KPI_DATA.DIGITIZATION_META = {
  costPerPage: 0.24, // € evitados por hoja (toner + papel + archivo)
  baselineMonths: 6,
};
